//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListaDeTarefas.Application.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListaDeTarefas.Application.Exceptions.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID não pode ser vazio..
        /// </summary>
        public static string ID_EMPTY {
            get {
                return ResourceManager.GetString("ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID deve ser maior que 0..
        /// </summary>
        public static string ID_GREATER_THAN_0 {
            get {
                return ResourceManager.GetString("ID_GREATER_THAN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O ID passado no parâmetro deve ser igual ao ID do body..
        /// </summary>
        public static string ID_PARAM_NOT_EQUAL_ID_BODY {
            get {
                return ResourceManager.GetString("ID_PARAM_NOT_EQUAL_ID_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;description&quot; não pode estar vazio..
        /// </summary>
        public static string TAREFA_DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("TAREFA_DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;description&quot; não deve ter mais de 150 caracteres..
        /// </summary>
        public static string TAREFA_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TAREFA_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;IsCompleted&quot; não pode ser vazio..
        /// </summary>
        public static string TAREFA_IS_COMPLETED_EMPTY {
            get {
                return ResourceManager.GetString("TAREFA_IS_COMPLETED_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma tarefa foi encontrada..
        /// </summary>
        public static string TAREFA_NOT_FOUND {
            get {
                return ResourceManager.GetString("TAREFA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;title&quot; não pode ser vazio..
        /// </summary>
        public static string TAREFA_TITLE_EMPTY {
            get {
                return ResourceManager.GetString("TAREFA_TITLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;title&quot; não deve ter mais de 50 caracteres..
        /// </summary>
        public static string TAREFA_TITLE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TAREFA_TITLE_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;email&quot; não pode ser vazio..
        /// </summary>
        public static string USER_EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("USER_EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;email&quot; deve estar no formato de e-mail..
        /// </summary>
        public static string USER_EMAIL_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("USER_EMAIL_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum usuário foi encontrado..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;password&quot; não pode estar vazio..
        /// </summary>
        public static string USER_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("USER_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;password&quot; deve ter até 20 caracteres..
        /// </summary>
        public static string USER_PASSWORD_MAX_LENGTH {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &quot;password&quot; deve ter pelo menos 5 caracteres..
        /// </summary>
        public static string USER_PASSWORD_MIN_LENGTH {
            get {
                return ResourceManager.GetString("USER_PASSWORD_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail e/ou senha incorretos..
        /// </summary>
        public static string USER_WRONG_CREDENTIALS {
            get {
                return ResourceManager.GetString("USER_WRONG_CREDENTIALS", resourceCulture);
            }
        }
    }
}
